// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gogo.proto

package test

import (
	fmt "fmt"
	_ "github.com/TheThingsIndustries/protoc-gen-go-field-setters/annotations"
	github_com_TheThingsIndustries_protoc_gen_go_field_setters_test_types "github.com/TheThingsIndustries/protoc-gen-go-field-setters/test/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MessageWithGoGoOptions struct {
	EUIWithCustomName                   []byte                                                                        `protobuf:"bytes,1,opt,name=eui_with_custom_name,json=euiWithCustomName,proto3" json:"eui_with_custom_name,omitempty"`
	EUIWithCustomNameAndType            *github_com_TheThingsIndustries_protoc_gen_go_field_setters_test_types.EUI64  `protobuf:"bytes,2,opt,name=eui_with_custom_name_and_type,json=euiWithCustomNameAndType,proto3,customtype=github.com/TheThingsIndustries/protoc-gen-go-field-setters/test/types.EUI64" json:"eui_with_custom_name_and_type,omitempty"`
	NonNullableEUIWithCustomNameAndType github_com_TheThingsIndustries_protoc_gen_go_field_setters_test_types.EUI64   `protobuf:"bytes,3,opt,name=non_nullable_eui_with_custom_name_and_type,json=nonNullableEuiWithCustomNameAndType,proto3,customtype=github.com/TheThingsIndustries/protoc-gen-go-field-setters/test/types.EUI64" json:"non_nullable_eui_with_custom_name_and_type"`
	EUIsWithCustomNameAndType           []github_com_TheThingsIndustries_protoc_gen_go_field_setters_test_types.EUI64 `protobuf:"bytes,4,rep,name=euis_with_custom_name_and_type,json=euisWithCustomNameAndType,proto3,customtype=github.com/TheThingsIndustries/protoc-gen-go-field-setters/test/types.EUI64" json:"euis_with_custom_name_and_type,omitempty"`
	Duration                            *time.Duration                                                                `protobuf:"bytes,5,opt,name=duration,proto3,stdduration" json:"duration,omitempty"`
	NonNullableDuration                 time.Duration                                                                 `protobuf:"bytes,6,opt,name=non_nullable_duration,json=nonNullableDuration,proto3,stdduration" json:"non_nullable_duration"`
	Timestamp                           *time.Time                                                                    `protobuf:"bytes,7,opt,name=timestamp,proto3,stdtime" json:"timestamp,omitempty"`
	NonNullableTimestamp                time.Time                                                                     `protobuf:"bytes,8,opt,name=non_nullable_timestamp,json=nonNullableTimestamp,proto3,stdtime" json:"non_nullable_timestamp"`
	XXX_NoUnkeyedLiteral                struct{}                                                                      `json:"-"`
	XXX_unrecognized                    []byte                                                                        `json:"-"`
	XXX_sizecache                       int32                                                                         `json:"-"`
}

func (m *MessageWithGoGoOptions) Reset()         { *m = MessageWithGoGoOptions{} }
func (m *MessageWithGoGoOptions) String() string { return proto.CompactTextString(m) }
func (*MessageWithGoGoOptions) ProtoMessage()    {}
func (*MessageWithGoGoOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_592445b5231bc2b9, []int{0}
}
func (m *MessageWithGoGoOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithGoGoOptions.Unmarshal(m, b)
}
func (m *MessageWithGoGoOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithGoGoOptions.Marshal(b, m, deterministic)
}
func (m *MessageWithGoGoOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithGoGoOptions.Merge(m, src)
}
func (m *MessageWithGoGoOptions) XXX_Size() int {
	return xxx_messageInfo_MessageWithGoGoOptions.Size(m)
}
func (m *MessageWithGoGoOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithGoGoOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithGoGoOptions proto.InternalMessageInfo

func (m *MessageWithGoGoOptions) GetEUIWithCustomName() []byte {
	if m != nil {
		return m.EUIWithCustomName
	}
	return nil
}

func (m *MessageWithGoGoOptions) GetDuration() *time.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *MessageWithGoGoOptions) GetNonNullableDuration() time.Duration {
	if m != nil {
		return m.NonNullableDuration
	}
	return 0
}

func (m *MessageWithGoGoOptions) GetTimestamp() *time.Time {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *MessageWithGoGoOptions) GetNonNullableTimestamp() time.Time {
	if m != nil {
		return m.NonNullableTimestamp
	}
	return time.Time{}
}

type MessageWithNullable struct {
	Sub                  SubMessage   `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub"`
	Subs                 []SubMessage `protobuf:"bytes,2,rep,name=subs,proto3" json:"subs"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MessageWithNullable) Reset()         { *m = MessageWithNullable{} }
func (m *MessageWithNullable) String() string { return proto.CompactTextString(m) }
func (*MessageWithNullable) ProtoMessage()    {}
func (*MessageWithNullable) Descriptor() ([]byte, []int) {
	return fileDescriptor_592445b5231bc2b9, []int{1}
}
func (m *MessageWithNullable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithNullable.Unmarshal(m, b)
}
func (m *MessageWithNullable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithNullable.Marshal(b, m, deterministic)
}
func (m *MessageWithNullable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithNullable.Merge(m, src)
}
func (m *MessageWithNullable) XXX_Size() int {
	return xxx_messageInfo_MessageWithNullable.Size(m)
}
func (m *MessageWithNullable) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithNullable.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithNullable proto.InternalMessageInfo

func (m *MessageWithNullable) GetSub() SubMessage {
	if m != nil {
		return m.Sub
	}
	return SubMessage{}
}

func (m *MessageWithNullable) GetSubs() []SubMessage {
	if m != nil {
		return m.Subs
	}
	return nil
}

type MessageWithEmbedded struct {
	*SubMessage          `protobuf:"bytes,1,opt,name=sub,proto3,embedded=sub" json:"sub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageWithEmbedded) Reset()         { *m = MessageWithEmbedded{} }
func (m *MessageWithEmbedded) String() string { return proto.CompactTextString(m) }
func (*MessageWithEmbedded) ProtoMessage()    {}
func (*MessageWithEmbedded) Descriptor() ([]byte, []int) {
	return fileDescriptor_592445b5231bc2b9, []int{2}
}
func (m *MessageWithEmbedded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithEmbedded.Unmarshal(m, b)
}
func (m *MessageWithEmbedded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithEmbedded.Marshal(b, m, deterministic)
}
func (m *MessageWithEmbedded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithEmbedded.Merge(m, src)
}
func (m *MessageWithEmbedded) XXX_Size() int {
	return xxx_messageInfo_MessageWithEmbedded.Size(m)
}
func (m *MessageWithEmbedded) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithEmbedded.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithEmbedded proto.InternalMessageInfo

type MessageWithNullableEmbedded struct {
	SubMessage           `protobuf:"bytes,1,opt,name=sub,proto3,embedded=sub" json:"sub"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageWithNullableEmbedded) Reset()         { *m = MessageWithNullableEmbedded{} }
func (m *MessageWithNullableEmbedded) String() string { return proto.CompactTextString(m) }
func (*MessageWithNullableEmbedded) ProtoMessage()    {}
func (*MessageWithNullableEmbedded) Descriptor() ([]byte, []int) {
	return fileDescriptor_592445b5231bc2b9, []int{3}
}
func (m *MessageWithNullableEmbedded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithNullableEmbedded.Unmarshal(m, b)
}
func (m *MessageWithNullableEmbedded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithNullableEmbedded.Marshal(b, m, deterministic)
}
func (m *MessageWithNullableEmbedded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithNullableEmbedded.Merge(m, src)
}
func (m *MessageWithNullableEmbedded) XXX_Size() int {
	return xxx_messageInfo_MessageWithNullableEmbedded.Size(m)
}
func (m *MessageWithNullableEmbedded) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithNullableEmbedded.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithNullableEmbedded proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MessageWithGoGoOptions)(nil), "thethings.fieldsetters.test.MessageWithGoGoOptions")
	proto.RegisterType((*MessageWithNullable)(nil), "thethings.fieldsetters.test.MessageWithNullable")
	proto.RegisterType((*MessageWithEmbedded)(nil), "thethings.fieldsetters.test.MessageWithEmbedded")
	proto.RegisterType((*MessageWithNullableEmbedded)(nil), "thethings.fieldsetters.test.MessageWithNullableEmbedded")
}

func init() { proto.RegisterFile("gogo.proto", fileDescriptor_592445b5231bc2b9) }

var fileDescriptor_592445b5231bc2b9 = []byte{
	// 591 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x5f, 0x6b, 0xd3, 0x50,
	0x18, 0x87, 0xcd, 0x5a, 0xb7, 0x7a, 0x36, 0x84, 0x65, 0x7f, 0x48, 0x3b, 0xb6, 0x94, 0xee, 0xc2,
	0x22, 0x34, 0x81, 0x29, 0xde, 0x08, 0x8e, 0x65, 0xd6, 0x52, 0xc4, 0x0a, 0xb5, 0x75, 0xb0, 0x9b,
	0x90, 0x34, 0xef, 0x92, 0x83, 0xc9, 0x39, 0xa5, 0xe7, 0x1c, 0x64, 0x7e, 0x0a, 0x2f, 0xf5, 0x2b,
	0x88, 0xe0, 0xd7, 0xd0, 0x3b, 0xc1, 0x3b, 0x2f, 0x2a, 0xec, 0x63, 0x78, 0x25, 0x39, 0x4d, 0xd2,
	0xd6, 0x76, 0x1d, 0xce, 0x5d, 0x36, 0xef, 0xef, 0x7d, 0xf2, 0xbc, 0x6f, 0xce, 0x29, 0x42, 0x3e,
	0xf5, 0xa9, 0xd1, 0x1f, 0x50, 0x4e, 0xd5, 0x1d, 0x1e, 0x00, 0x0f, 0x30, 0xf1, 0x99, 0x71, 0x86,
	0x21, 0xf4, 0x18, 0x70, 0x0e, 0x03, 0x66, 0x70, 0x60, 0xbc, 0xb4, 0xee, 0x10, 0x42, 0xb9, 0xc3,
	0x31, 0x25, 0x6c, 0x94, 0x2f, 0xed, 0x62, 0xc2, 0x61, 0x40, 0x9c, 0xd0, 0x8c, 0x21, 0xf2, 0x99,
	0x39, 0xc6, 0x95, 0xee, 0x46, 0xc0, 0x98, 0xe3, 0x43, 0x1a, 0xdf, 0xf3, 0x29, 0xf5, 0x43, 0x30,
	0xe5, 0x2f, 0x57, 0x9c, 0x99, 0x9e, 0x18, 0x48, 0x5e, 0x52, 0xd7, 0xff, 0xae, 0x73, 0x1c, 0x01,
	0xe3, 0x4e, 0xd4, 0x1f, 0x05, 0x2a, 0xdf, 0x56, 0xd0, 0xf6, 0x8b, 0x11, 0xf3, 0x04, 0xf3, 0xa0,
	0x41, 0x1b, 0xf4, 0x65, 0x5f, 0x0a, 0xa9, 0xcf, 0xd0, 0x26, 0x08, 0x6c, 0xbf, 0xc5, 0x3c, 0xb0,
	0x7b, 0x82, 0x71, 0x1a, 0xd9, 0xc4, 0x89, 0x40, 0x53, 0xca, 0x4a, 0x75, 0xcd, 0xda, 0xba, 0x18,
	0xea, 0xeb, 0xf5, 0x6e, 0x33, 0xee, 0x3a, 0x96, 0xd5, 0x96, 0x13, 0x41, 0x7b, 0x1d, 0x04, 0x9e,
	0x7e, 0xa4, 0x7e, 0x56, 0xd0, 0xee, 0x3c, 0x90, 0xed, 0x10, 0xcf, 0xe6, 0xe7, 0x7d, 0xd0, 0x96,
	0x24, 0xf1, 0xcd, 0xcf, 0xa1, 0xfe, 0xdc, 0xc7, 0x3c, 0x10, 0xae, 0xd1, 0xa3, 0x91, 0xd9, 0x09,
	0xa0, 0x23, 0x37, 0xd7, 0x24, 0x9e, 0x60, 0x7c, 0x80, 0x81, 0x8d, 0xe6, 0xe8, 0xd5, 0x7c, 0x20,
	0x35, 0x9f, 0xd6, 0xe4, 0x46, 0x6b, 0xc9, 0x4a, 0xcd, 0x78, 0xa5, 0x66, 0xcc, 0x63, 0x46, 0xbd,
	0xdb, 0x7c, 0xf4, 0xf0, 0x62, 0xa8, 0x6b, 0x33, 0x82, 0x47, 0xc4, 0xeb, 0x9c, 0xf7, 0xa1, 0xad,
	0xcd, 0x78, 0x26, 0x15, 0xf5, 0x87, 0x82, 0xee, 0x13, 0x4a, 0x6c, 0x22, 0xc2, 0xd0, 0x71, 0x43,
	0xb0, 0x17, 0xbb, 0xe7, 0xa4, 0xfb, 0xbb, 0xaf, 0x43, 0xfd, 0xd6, 0xcd, 0xfb, 0xef, 0xb7, 0x28,
	0x69, 0x25, 0x1e, 0x97, 0x8e, 0xb2, 0x4f, 0x26, 0x42, 0x97, 0x4d, 0xf5, 0x45, 0x41, 0x7b, 0x20,
	0x30, 0x5b, 0x30, 0x49, 0xbe, 0x9c, 0xab, 0xae, 0x59, 0xe1, 0xcd, 0x4f, 0x51, 0xac, 0x77, 0x9b,
	0x6c, 0xbe, 0x7b, 0x31, 0x76, 0x9a, 0x6f, 0xfc, 0x18, 0x15, 0xd2, 0xc3, 0xac, 0xdd, 0x2e, 0x2b,
	0xd5, 0xd5, 0x83, 0xa2, 0x31, 0x3a, 0xcd, 0x46, 0x7a, 0x9a, 0x8d, 0xa7, 0x49, 0xc0, 0xca, 0x7f,
	0xf8, 0xa5, 0x2b, 0xed, 0xac, 0x41, 0x3d, 0x41, 0x5b, 0x53, 0xdf, 0x30, 0x23, 0x2d, 0x5f, 0x45,
	0x2a, 0xc4, 0x5f, 0x52, 0xd2, 0x36, 0x26, 0xf6, 0x9a, 0x96, 0xd5, 0x27, 0xe8, 0x4e, 0x76, 0x85,
	0xb4, 0x15, 0x09, 0x2b, 0xcd, 0xc0, 0x3a, 0x69, 0xc2, 0xca, 0xbf, 0x8f, 0x49, 0xe3, 0x16, 0xf5,
	0x14, 0x6d, 0x4f, 0x89, 0x8d, 0x61, 0x85, 0x2b, 0x61, 0x52, 0x4d, 0x02, 0x37, 0x27, 0xd4, 0xb2,
	0x7a, 0xe5, 0xa3, 0x82, 0x36, 0x26, 0xee, 0x72, 0x1a, 0x50, 0x0f, 0x51, 0x8e, 0x09, 0x57, 0xde,
	0xdb, 0xd5, 0x83, 0x7b, 0xc6, 0x82, 0x7f, 0x24, 0xe3, 0x95, 0x70, 0x13, 0x82, 0x95, 0x8f, 0xdf,
	0xd6, 0x8e, 0x3b, 0xd5, 0x23, 0x94, 0x67, 0xc2, 0x65, 0xda, 0x52, 0x39, 0xf7, 0xef, 0x04, 0xd9,
	0x5a, 0x79, 0x3d, 0xa5, 0x56, 0x8f, 0x5c, 0xf0, 0x3c, 0xf0, 0xae, 0xab, 0xf6, 0x7d, 0xa8, 0x2b,
	0x52, 0xad, 0xe2, 0xa2, 0x9d, 0x39, 0x23, 0x67, 0xfc, 0xe3, 0x6b, 0xf1, 0xe5, 0xa2, 0xb3, 0x77,
	0x58, 0x8d, 0xdf, 0x9f, 0x8a, 0x4b, 0x05, 0xe5, 0xf4, 0xf0, 0x3f, 0xaf, 0x85, 0xbb, 0x2c, 0x13,
	0x0f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x77, 0x56, 0xea, 0x14, 0x21, 0x06, 0x00, 0x00,
}
