// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: scalars.proto

package test

import (
	fmt "fmt"
	_ "github.com/TheThingsIndustries/protoc-gen-go-field-setters/annotations"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MessageWithScalars struct {
	DoubleValue          float64   `protobuf:"fixed64,1,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	DoubleValues         []float64 `protobuf:"fixed64,2,rep,packed,name=double_values,json=doubleValues,proto3" json:"double_values,omitempty"`
	FloatValue           float32   `protobuf:"fixed32,3,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	FloatValues          []float32 `protobuf:"fixed32,4,rep,packed,name=float_values,json=floatValues,proto3" json:"float_values,omitempty"`
	Int32Value           int32     `protobuf:"varint,5,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Int32Values          []int32   `protobuf:"varint,6,rep,packed,name=int32_values,json=int32Values,proto3" json:"int32_values,omitempty"`
	Int64Value           int64     `protobuf:"varint,7,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Int64Values          []int64   `protobuf:"varint,8,rep,packed,name=int64_values,json=int64Values,proto3" json:"int64_values,omitempty"`
	Uint32Value          uint32    `protobuf:"varint,9,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	Uint32Values         []uint32  `protobuf:"varint,10,rep,packed,name=uint32_values,json=uint32Values,proto3" json:"uint32_values,omitempty"`
	Uint64Value          uint64    `protobuf:"varint,11,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	Uint64Values         []uint64  `protobuf:"varint,12,rep,packed,name=uint64_values,json=uint64Values,proto3" json:"uint64_values,omitempty"`
	Sint32Value          int32     `protobuf:"zigzag32,13,opt,name=sint32_value,json=sint32Value,proto3" json:"sint32_value,omitempty"`
	Sint32Values         []int32   `protobuf:"zigzag32,14,rep,packed,name=sint32_values,json=sint32Values,proto3" json:"sint32_values,omitempty"`
	Sint64Value          int64     `protobuf:"zigzag64,15,opt,name=sint64_value,json=sint64Value,proto3" json:"sint64_value,omitempty"`
	Sint64Values         []int64   `protobuf:"zigzag64,16,rep,packed,name=sint64_values,json=sint64Values,proto3" json:"sint64_values,omitempty"`
	Fixed32Value         uint32    `protobuf:"fixed32,17,opt,name=fixed32_value,json=fixed32Value,proto3" json:"fixed32_value,omitempty"`
	Fixed32Values        []uint32  `protobuf:"fixed32,18,rep,packed,name=fixed32_values,json=fixed32Values,proto3" json:"fixed32_values,omitempty"`
	Fixed64Value         uint64    `protobuf:"fixed64,19,opt,name=fixed64_value,json=fixed64Value,proto3" json:"fixed64_value,omitempty"`
	Fixed64Values        []uint64  `protobuf:"fixed64,20,rep,packed,name=fixed64_values,json=fixed64Values,proto3" json:"fixed64_values,omitempty"`
	Sfixed32Value        int32     `protobuf:"fixed32,21,opt,name=sfixed32_value,json=sfixed32Value,proto3" json:"sfixed32_value,omitempty"`
	Sfixed32Values       []int32   `protobuf:"fixed32,22,rep,packed,name=sfixed32_values,json=sfixed32Values,proto3" json:"sfixed32_values,omitempty"`
	Sfixed64Value        int64     `protobuf:"fixed64,23,opt,name=sfixed64_value,json=sfixed64Value,proto3" json:"sfixed64_value,omitempty"`
	Sfixed64Values       []int64   `protobuf:"fixed64,24,rep,packed,name=sfixed64_values,json=sfixed64Values,proto3" json:"sfixed64_values,omitempty"`
	BoolValue            bool      `protobuf:"varint,25,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	BoolValues           []bool    `protobuf:"varint,26,rep,packed,name=bool_values,json=boolValues,proto3" json:"bool_values,omitempty"`
	StringValue          string    `protobuf:"bytes,27,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	StringValues         []string  `protobuf:"bytes,28,rep,name=string_values,json=stringValues,proto3" json:"string_values,omitempty"`
	BytesValue           []byte    `protobuf:"bytes,29,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	BytesValues          [][]byte  `protobuf:"bytes,30,rep,name=bytes_values,json=bytesValues,proto3" json:"bytes_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MessageWithScalars) Reset()         { *m = MessageWithScalars{} }
func (m *MessageWithScalars) String() string { return proto.CompactTextString(m) }
func (*MessageWithScalars) ProtoMessage()    {}
func (*MessageWithScalars) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d1bcd1a4bdfc194, []int{0}
}
func (m *MessageWithScalars) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithScalars.Unmarshal(m, b)
}
func (m *MessageWithScalars) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithScalars.Marshal(b, m, deterministic)
}
func (m *MessageWithScalars) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithScalars.Merge(m, src)
}
func (m *MessageWithScalars) XXX_Size() int {
	return xxx_messageInfo_MessageWithScalars.Size(m)
}
func (m *MessageWithScalars) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithScalars.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithScalars proto.InternalMessageInfo

func (m *MessageWithScalars) GetDoubleValue() float64 {
	if m != nil {
		return m.DoubleValue
	}
	return 0
}

func (m *MessageWithScalars) GetDoubleValues() []float64 {
	if m != nil {
		return m.DoubleValues
	}
	return nil
}

func (m *MessageWithScalars) GetFloatValue() float32 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *MessageWithScalars) GetFloatValues() []float32 {
	if m != nil {
		return m.FloatValues
	}
	return nil
}

func (m *MessageWithScalars) GetInt32Value() int32 {
	if m != nil {
		return m.Int32Value
	}
	return 0
}

func (m *MessageWithScalars) GetInt32Values() []int32 {
	if m != nil {
		return m.Int32Values
	}
	return nil
}

func (m *MessageWithScalars) GetInt64Value() int64 {
	if m != nil {
		return m.Int64Value
	}
	return 0
}

func (m *MessageWithScalars) GetInt64Values() []int64 {
	if m != nil {
		return m.Int64Values
	}
	return nil
}

func (m *MessageWithScalars) GetUint32Value() uint32 {
	if m != nil {
		return m.Uint32Value
	}
	return 0
}

func (m *MessageWithScalars) GetUint32Values() []uint32 {
	if m != nil {
		return m.Uint32Values
	}
	return nil
}

func (m *MessageWithScalars) GetUint64Value() uint64 {
	if m != nil {
		return m.Uint64Value
	}
	return 0
}

func (m *MessageWithScalars) GetUint64Values() []uint64 {
	if m != nil {
		return m.Uint64Values
	}
	return nil
}

func (m *MessageWithScalars) GetSint32Value() int32 {
	if m != nil {
		return m.Sint32Value
	}
	return 0
}

func (m *MessageWithScalars) GetSint32Values() []int32 {
	if m != nil {
		return m.Sint32Values
	}
	return nil
}

func (m *MessageWithScalars) GetSint64Value() int64 {
	if m != nil {
		return m.Sint64Value
	}
	return 0
}

func (m *MessageWithScalars) GetSint64Values() []int64 {
	if m != nil {
		return m.Sint64Values
	}
	return nil
}

func (m *MessageWithScalars) GetFixed32Value() uint32 {
	if m != nil {
		return m.Fixed32Value
	}
	return 0
}

func (m *MessageWithScalars) GetFixed32Values() []uint32 {
	if m != nil {
		return m.Fixed32Values
	}
	return nil
}

func (m *MessageWithScalars) GetFixed64Value() uint64 {
	if m != nil {
		return m.Fixed64Value
	}
	return 0
}

func (m *MessageWithScalars) GetFixed64Values() []uint64 {
	if m != nil {
		return m.Fixed64Values
	}
	return nil
}

func (m *MessageWithScalars) GetSfixed32Value() int32 {
	if m != nil {
		return m.Sfixed32Value
	}
	return 0
}

func (m *MessageWithScalars) GetSfixed32Values() []int32 {
	if m != nil {
		return m.Sfixed32Values
	}
	return nil
}

func (m *MessageWithScalars) GetSfixed64Value() int64 {
	if m != nil {
		return m.Sfixed64Value
	}
	return 0
}

func (m *MessageWithScalars) GetSfixed64Values() []int64 {
	if m != nil {
		return m.Sfixed64Values
	}
	return nil
}

func (m *MessageWithScalars) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *MessageWithScalars) GetBoolValues() []bool {
	if m != nil {
		return m.BoolValues
	}
	return nil
}

func (m *MessageWithScalars) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *MessageWithScalars) GetStringValues() []string {
	if m != nil {
		return m.StringValues
	}
	return nil
}

func (m *MessageWithScalars) GetBytesValue() []byte {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

func (m *MessageWithScalars) GetBytesValues() [][]byte {
	if m != nil {
		return m.BytesValues
	}
	return nil
}

type MessageWithOneofScalars struct {
	// Types that are valid to be assigned to Value:
	//	*MessageWithOneofScalars_DoubleValue
	//	*MessageWithOneofScalars_FloatValue
	//	*MessageWithOneofScalars_Int32Value
	//	*MessageWithOneofScalars_Int64Value
	//	*MessageWithOneofScalars_Uint32Value
	//	*MessageWithOneofScalars_Uint64Value
	//	*MessageWithOneofScalars_Sint32Value
	//	*MessageWithOneofScalars_Sint64Value
	//	*MessageWithOneofScalars_Fixed32Value
	//	*MessageWithOneofScalars_Fixed64Value
	//	*MessageWithOneofScalars_Sfixed32Value
	//	*MessageWithOneofScalars_Sfixed64Value
	//	*MessageWithOneofScalars_BoolValue
	//	*MessageWithOneofScalars_StringValue
	//	*MessageWithOneofScalars_BytesValue
	Value                isMessageWithOneofScalars_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *MessageWithOneofScalars) Reset()         { *m = MessageWithOneofScalars{} }
func (m *MessageWithOneofScalars) String() string { return proto.CompactTextString(m) }
func (*MessageWithOneofScalars) ProtoMessage()    {}
func (*MessageWithOneofScalars) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d1bcd1a4bdfc194, []int{1}
}
func (m *MessageWithOneofScalars) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithOneofScalars.Unmarshal(m, b)
}
func (m *MessageWithOneofScalars) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithOneofScalars.Marshal(b, m, deterministic)
}
func (m *MessageWithOneofScalars) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithOneofScalars.Merge(m, src)
}
func (m *MessageWithOneofScalars) XXX_Size() int {
	return xxx_messageInfo_MessageWithOneofScalars.Size(m)
}
func (m *MessageWithOneofScalars) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithOneofScalars.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithOneofScalars proto.InternalMessageInfo

type isMessageWithOneofScalars_Value interface {
	isMessageWithOneofScalars_Value()
}

type MessageWithOneofScalars_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,1,opt,name=double_value,json=doubleValue,proto3,oneof" json:"double_value,omitempty"`
}
type MessageWithOneofScalars_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,2,opt,name=float_value,json=floatValue,proto3,oneof" json:"float_value,omitempty"`
}
type MessageWithOneofScalars_Int32Value struct {
	Int32Value int32 `protobuf:"varint,3,opt,name=int32_value,json=int32Value,proto3,oneof" json:"int32_value,omitempty"`
}
type MessageWithOneofScalars_Int64Value struct {
	Int64Value int64 `protobuf:"varint,4,opt,name=int64_value,json=int64Value,proto3,oneof" json:"int64_value,omitempty"`
}
type MessageWithOneofScalars_Uint32Value struct {
	Uint32Value uint32 `protobuf:"varint,5,opt,name=uint32_value,json=uint32Value,proto3,oneof" json:"uint32_value,omitempty"`
}
type MessageWithOneofScalars_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value,proto3,oneof" json:"uint64_value,omitempty"`
}
type MessageWithOneofScalars_Sint32Value struct {
	Sint32Value int32 `protobuf:"zigzag32,7,opt,name=sint32_value,json=sint32Value,proto3,oneof" json:"sint32_value,omitempty"`
}
type MessageWithOneofScalars_Sint64Value struct {
	Sint64Value int64 `protobuf:"zigzag64,8,opt,name=sint64_value,json=sint64Value,proto3,oneof" json:"sint64_value,omitempty"`
}
type MessageWithOneofScalars_Fixed32Value struct {
	Fixed32Value uint32 `protobuf:"fixed32,9,opt,name=fixed32_value,json=fixed32Value,proto3,oneof" json:"fixed32_value,omitempty"`
}
type MessageWithOneofScalars_Fixed64Value struct {
	Fixed64Value uint64 `protobuf:"fixed64,10,opt,name=fixed64_value,json=fixed64Value,proto3,oneof" json:"fixed64_value,omitempty"`
}
type MessageWithOneofScalars_Sfixed32Value struct {
	Sfixed32Value int32 `protobuf:"fixed32,11,opt,name=sfixed32_value,json=sfixed32Value,proto3,oneof" json:"sfixed32_value,omitempty"`
}
type MessageWithOneofScalars_Sfixed64Value struct {
	Sfixed64Value int64 `protobuf:"fixed64,12,opt,name=sfixed64_value,json=sfixed64Value,proto3,oneof" json:"sfixed64_value,omitempty"`
}
type MessageWithOneofScalars_BoolValue struct {
	BoolValue bool `protobuf:"varint,13,opt,name=bool_value,json=boolValue,proto3,oneof" json:"bool_value,omitempty"`
}
type MessageWithOneofScalars_StringValue struct {
	StringValue string `protobuf:"bytes,14,opt,name=string_value,json=stringValue,proto3,oneof" json:"string_value,omitempty"`
}
type MessageWithOneofScalars_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,15,opt,name=bytes_value,json=bytesValue,proto3,oneof" json:"bytes_value,omitempty"`
}

func (*MessageWithOneofScalars_DoubleValue) isMessageWithOneofScalars_Value()   {}
func (*MessageWithOneofScalars_FloatValue) isMessageWithOneofScalars_Value()    {}
func (*MessageWithOneofScalars_Int32Value) isMessageWithOneofScalars_Value()    {}
func (*MessageWithOneofScalars_Int64Value) isMessageWithOneofScalars_Value()    {}
func (*MessageWithOneofScalars_Uint32Value) isMessageWithOneofScalars_Value()   {}
func (*MessageWithOneofScalars_Uint64Value) isMessageWithOneofScalars_Value()   {}
func (*MessageWithOneofScalars_Sint32Value) isMessageWithOneofScalars_Value()   {}
func (*MessageWithOneofScalars_Sint64Value) isMessageWithOneofScalars_Value()   {}
func (*MessageWithOneofScalars_Fixed32Value) isMessageWithOneofScalars_Value()  {}
func (*MessageWithOneofScalars_Fixed64Value) isMessageWithOneofScalars_Value()  {}
func (*MessageWithOneofScalars_Sfixed32Value) isMessageWithOneofScalars_Value() {}
func (*MessageWithOneofScalars_Sfixed64Value) isMessageWithOneofScalars_Value() {}
func (*MessageWithOneofScalars_BoolValue) isMessageWithOneofScalars_Value()     {}
func (*MessageWithOneofScalars_StringValue) isMessageWithOneofScalars_Value()   {}
func (*MessageWithOneofScalars_BytesValue) isMessageWithOneofScalars_Value()    {}

func (m *MessageWithOneofScalars) GetValue() isMessageWithOneofScalars_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *MessageWithOneofScalars) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*MessageWithOneofScalars_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *MessageWithOneofScalars) GetFloatValue() float32 {
	if x, ok := m.GetValue().(*MessageWithOneofScalars_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *MessageWithOneofScalars) GetInt32Value() int32 {
	if x, ok := m.GetValue().(*MessageWithOneofScalars_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (m *MessageWithOneofScalars) GetInt64Value() int64 {
	if x, ok := m.GetValue().(*MessageWithOneofScalars_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (m *MessageWithOneofScalars) GetUint32Value() uint32 {
	if x, ok := m.GetValue().(*MessageWithOneofScalars_Uint32Value); ok {
		return x.Uint32Value
	}
	return 0
}

func (m *MessageWithOneofScalars) GetUint64Value() uint64 {
	if x, ok := m.GetValue().(*MessageWithOneofScalars_Uint64Value); ok {
		return x.Uint64Value
	}
	return 0
}

func (m *MessageWithOneofScalars) GetSint32Value() int32 {
	if x, ok := m.GetValue().(*MessageWithOneofScalars_Sint32Value); ok {
		return x.Sint32Value
	}
	return 0
}

func (m *MessageWithOneofScalars) GetSint64Value() int64 {
	if x, ok := m.GetValue().(*MessageWithOneofScalars_Sint64Value); ok {
		return x.Sint64Value
	}
	return 0
}

func (m *MessageWithOneofScalars) GetFixed32Value() uint32 {
	if x, ok := m.GetValue().(*MessageWithOneofScalars_Fixed32Value); ok {
		return x.Fixed32Value
	}
	return 0
}

func (m *MessageWithOneofScalars) GetFixed64Value() uint64 {
	if x, ok := m.GetValue().(*MessageWithOneofScalars_Fixed64Value); ok {
		return x.Fixed64Value
	}
	return 0
}

func (m *MessageWithOneofScalars) GetSfixed32Value() int32 {
	if x, ok := m.GetValue().(*MessageWithOneofScalars_Sfixed32Value); ok {
		return x.Sfixed32Value
	}
	return 0
}

func (m *MessageWithOneofScalars) GetSfixed64Value() int64 {
	if x, ok := m.GetValue().(*MessageWithOneofScalars_Sfixed64Value); ok {
		return x.Sfixed64Value
	}
	return 0
}

func (m *MessageWithOneofScalars) GetBoolValue() bool {
	if x, ok := m.GetValue().(*MessageWithOneofScalars_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *MessageWithOneofScalars) GetStringValue() string {
	if x, ok := m.GetValue().(*MessageWithOneofScalars_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *MessageWithOneofScalars) GetBytesValue() []byte {
	if x, ok := m.GetValue().(*MessageWithOneofScalars_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MessageWithOneofScalars) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MessageWithOneofScalars_DoubleValue)(nil),
		(*MessageWithOneofScalars_FloatValue)(nil),
		(*MessageWithOneofScalars_Int32Value)(nil),
		(*MessageWithOneofScalars_Int64Value)(nil),
		(*MessageWithOneofScalars_Uint32Value)(nil),
		(*MessageWithOneofScalars_Uint64Value)(nil),
		(*MessageWithOneofScalars_Sint32Value)(nil),
		(*MessageWithOneofScalars_Sint64Value)(nil),
		(*MessageWithOneofScalars_Fixed32Value)(nil),
		(*MessageWithOneofScalars_Fixed64Value)(nil),
		(*MessageWithOneofScalars_Sfixed32Value)(nil),
		(*MessageWithOneofScalars_Sfixed64Value)(nil),
		(*MessageWithOneofScalars_BoolValue)(nil),
		(*MessageWithOneofScalars_StringValue)(nil),
		(*MessageWithOneofScalars_BytesValue)(nil),
	}
}

type MessageWithScalarMaps struct {
	StringDoubleMap      map[string]float64 `protobuf:"bytes,1,rep,name=string_double_map,json=stringDoubleMap,proto3" json:"string_double_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	StringFloatMap       map[string]float32 `protobuf:"bytes,3,rep,name=string_float_map,json=stringFloatMap,proto3" json:"string_float_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	StringInt32Map       map[string]int32   `protobuf:"bytes,5,rep,name=string_int32_map,json=stringInt32Map,proto3" json:"string_int32_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Int32StringMap       map[int32]string   `protobuf:"bytes,6,rep,name=int32_string_map,json=int32StringMap,proto3" json:"int32_string_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringInt64Map       map[string]int64   `protobuf:"bytes,7,rep,name=string_int64_map,json=stringInt64Map,proto3" json:"string_int64_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Int64StringMap       map[int64]string   `protobuf:"bytes,8,rep,name=int64_string_map,json=int64StringMap,proto3" json:"int64_string_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringUint32Map      map[string]uint32  `protobuf:"bytes,9,rep,name=string_uint32_map,json=stringUint32Map,proto3" json:"string_uint32_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Uint32StringMap      map[uint32]string  `protobuf:"bytes,10,rep,name=uint32_string_map,json=uint32StringMap,proto3" json:"uint32_string_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringUint64Map      map[string]uint64  `protobuf:"bytes,11,rep,name=string_uint64_map,json=stringUint64Map,proto3" json:"string_uint64_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Uint64StringMap      map[uint64]string  `protobuf:"bytes,12,rep,name=uint64_string_map,json=uint64StringMap,proto3" json:"uint64_string_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringSint32Map      map[string]int32   `protobuf:"bytes,13,rep,name=string_sint32_map,json=stringSint32Map,proto3" json:"string_sint32_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"zigzag32,2,opt,name=value,proto3"`
	Sint32StringMap      map[int32]string   `protobuf:"bytes,14,rep,name=sint32_string_map,json=sint32StringMap,proto3" json:"sint32_string_map,omitempty" protobuf_key:"zigzag32,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringSint64Map      map[string]int64   `protobuf:"bytes,15,rep,name=string_sint64_map,json=stringSint64Map,proto3" json:"string_sint64_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"zigzag64,2,opt,name=value,proto3"`
	Sint64StringMap      map[int64]string   `protobuf:"bytes,16,rep,name=sint64_string_map,json=sint64StringMap,proto3" json:"sint64_string_map,omitempty" protobuf_key:"zigzag64,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringFixed32Map     map[string]uint32  `protobuf:"bytes,17,rep,name=string_fixed32_map,json=stringFixed32Map,proto3" json:"string_fixed32_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	Fixed32StringMap     map[uint32]string  `protobuf:"bytes,18,rep,name=fixed32_string_map,json=fixed32StringMap,proto3" json:"fixed32_string_map,omitempty" protobuf_key:"fixed32,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringFixed64Map     map[string]uint64  `protobuf:"bytes,19,rep,name=string_fixed64_map,json=stringFixed64Map,proto3" json:"string_fixed64_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	Fixed64StringMap     map[uint64]string  `protobuf:"bytes,20,rep,name=fixed64_string_map,json=fixed64StringMap,proto3" json:"fixed64_string_map,omitempty" protobuf_key:"fixed64,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringSfixed32Map    map[string]int32   `protobuf:"bytes,21,rep,name=string_sfixed32_map,json=stringSfixed32Map,proto3" json:"string_sfixed32_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	Sfixed32StringMap    map[int32]string   `protobuf:"bytes,22,rep,name=sfixed32_string_map,json=sfixed32StringMap,proto3" json:"sfixed32_string_map,omitempty" protobuf_key:"fixed32,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringSfixed64Map    map[string]int64   `protobuf:"bytes,23,rep,name=string_sfixed64_map,json=stringSfixed64Map,proto3" json:"string_sfixed64_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	Sfixed64StringMap    map[int64]string   `protobuf:"bytes,24,rep,name=sfixed64_string_map,json=sfixed64StringMap,proto3" json:"sfixed64_string_map,omitempty" protobuf_key:"fixed64,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringBoolMap        map[string]bool    `protobuf:"bytes,25,rep,name=string_bool_map,json=stringBoolMap,proto3" json:"string_bool_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	BoolStringMap        map[bool]string    `protobuf:"bytes,26,rep,name=bool_string_map,json=boolStringMap,proto3" json:"bool_string_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringStringMap      map[string]string  `protobuf:"bytes,27,rep,name=string_string_map,json=stringStringMap,proto3" json:"string_string_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringBytesMap       map[string][]byte  `protobuf:"bytes,29,rep,name=string_bytes_map,json=stringBytesMap,proto3" json:"string_bytes_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MessageWithScalarMaps) Reset()         { *m = MessageWithScalarMaps{} }
func (m *MessageWithScalarMaps) String() string { return proto.CompactTextString(m) }
func (*MessageWithScalarMaps) ProtoMessage()    {}
func (*MessageWithScalarMaps) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d1bcd1a4bdfc194, []int{2}
}
func (m *MessageWithScalarMaps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithScalarMaps.Unmarshal(m, b)
}
func (m *MessageWithScalarMaps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithScalarMaps.Marshal(b, m, deterministic)
}
func (m *MessageWithScalarMaps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithScalarMaps.Merge(m, src)
}
func (m *MessageWithScalarMaps) XXX_Size() int {
	return xxx_messageInfo_MessageWithScalarMaps.Size(m)
}
func (m *MessageWithScalarMaps) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithScalarMaps.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithScalarMaps proto.InternalMessageInfo

func (m *MessageWithScalarMaps) GetStringDoubleMap() map[string]float64 {
	if m != nil {
		return m.StringDoubleMap
	}
	return nil
}

func (m *MessageWithScalarMaps) GetStringFloatMap() map[string]float32 {
	if m != nil {
		return m.StringFloatMap
	}
	return nil
}

func (m *MessageWithScalarMaps) GetStringInt32Map() map[string]int32 {
	if m != nil {
		return m.StringInt32Map
	}
	return nil
}

func (m *MessageWithScalarMaps) GetInt32StringMap() map[int32]string {
	if m != nil {
		return m.Int32StringMap
	}
	return nil
}

func (m *MessageWithScalarMaps) GetStringInt64Map() map[string]int64 {
	if m != nil {
		return m.StringInt64Map
	}
	return nil
}

func (m *MessageWithScalarMaps) GetInt64StringMap() map[int64]string {
	if m != nil {
		return m.Int64StringMap
	}
	return nil
}

func (m *MessageWithScalarMaps) GetStringUint32Map() map[string]uint32 {
	if m != nil {
		return m.StringUint32Map
	}
	return nil
}

func (m *MessageWithScalarMaps) GetUint32StringMap() map[uint32]string {
	if m != nil {
		return m.Uint32StringMap
	}
	return nil
}

func (m *MessageWithScalarMaps) GetStringUint64Map() map[string]uint64 {
	if m != nil {
		return m.StringUint64Map
	}
	return nil
}

func (m *MessageWithScalarMaps) GetUint64StringMap() map[uint64]string {
	if m != nil {
		return m.Uint64StringMap
	}
	return nil
}

func (m *MessageWithScalarMaps) GetStringSint32Map() map[string]int32 {
	if m != nil {
		return m.StringSint32Map
	}
	return nil
}

func (m *MessageWithScalarMaps) GetSint32StringMap() map[int32]string {
	if m != nil {
		return m.Sint32StringMap
	}
	return nil
}

func (m *MessageWithScalarMaps) GetStringSint64Map() map[string]int64 {
	if m != nil {
		return m.StringSint64Map
	}
	return nil
}

func (m *MessageWithScalarMaps) GetSint64StringMap() map[int64]string {
	if m != nil {
		return m.Sint64StringMap
	}
	return nil
}

func (m *MessageWithScalarMaps) GetStringFixed32Map() map[string]uint32 {
	if m != nil {
		return m.StringFixed32Map
	}
	return nil
}

func (m *MessageWithScalarMaps) GetFixed32StringMap() map[uint32]string {
	if m != nil {
		return m.Fixed32StringMap
	}
	return nil
}

func (m *MessageWithScalarMaps) GetStringFixed64Map() map[string]uint64 {
	if m != nil {
		return m.StringFixed64Map
	}
	return nil
}

func (m *MessageWithScalarMaps) GetFixed64StringMap() map[uint64]string {
	if m != nil {
		return m.Fixed64StringMap
	}
	return nil
}

func (m *MessageWithScalarMaps) GetStringSfixed32Map() map[string]int32 {
	if m != nil {
		return m.StringSfixed32Map
	}
	return nil
}

func (m *MessageWithScalarMaps) GetSfixed32StringMap() map[int32]string {
	if m != nil {
		return m.Sfixed32StringMap
	}
	return nil
}

func (m *MessageWithScalarMaps) GetStringSfixed64Map() map[string]int64 {
	if m != nil {
		return m.StringSfixed64Map
	}
	return nil
}

func (m *MessageWithScalarMaps) GetSfixed64StringMap() map[int64]string {
	if m != nil {
		return m.Sfixed64StringMap
	}
	return nil
}

func (m *MessageWithScalarMaps) GetStringBoolMap() map[string]bool {
	if m != nil {
		return m.StringBoolMap
	}
	return nil
}

func (m *MessageWithScalarMaps) GetBoolStringMap() map[bool]string {
	if m != nil {
		return m.BoolStringMap
	}
	return nil
}

func (m *MessageWithScalarMaps) GetStringStringMap() map[string]string {
	if m != nil {
		return m.StringStringMap
	}
	return nil
}

func (m *MessageWithScalarMaps) GetStringBytesMap() map[string][]byte {
	if m != nil {
		return m.StringBytesMap
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageWithScalars)(nil), "thethings.fieldsetters.test.MessageWithScalars")
	proto.RegisterType((*MessageWithOneofScalars)(nil), "thethings.fieldsetters.test.MessageWithOneofScalars")
	proto.RegisterType((*MessageWithScalarMaps)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps")
	proto.RegisterMapType((map[bool]string)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.BoolStringMapEntry")
	proto.RegisterMapType((map[uint32]string)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.Fixed32StringMapEntry")
	proto.RegisterMapType((map[uint64]string)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.Fixed64StringMapEntry")
	proto.RegisterMapType((map[int32]string)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.Int32StringMapEntry")
	proto.RegisterMapType((map[int64]string)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.Int64StringMapEntry")
	proto.RegisterMapType((map[int32]string)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.Sfixed32StringMapEntry")
	proto.RegisterMapType((map[int64]string)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.Sfixed64StringMapEntry")
	proto.RegisterMapType((map[int32]string)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.Sint32StringMapEntry")
	proto.RegisterMapType((map[int64]string)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.Sint64StringMapEntry")
	proto.RegisterMapType((map[string]bool)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.StringBoolMapEntry")
	proto.RegisterMapType((map[string][]byte)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.StringBytesMapEntry")
	proto.RegisterMapType((map[string]float64)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.StringDoubleMapEntry")
	proto.RegisterMapType((map[string]uint32)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.StringFixed32MapEntry")
	proto.RegisterMapType((map[string]uint64)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.StringFixed64MapEntry")
	proto.RegisterMapType((map[string]float32)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.StringFloatMapEntry")
	proto.RegisterMapType((map[string]int32)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.StringInt32MapEntry")
	proto.RegisterMapType((map[string]int64)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.StringInt64MapEntry")
	proto.RegisterMapType((map[string]int32)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.StringSfixed32MapEntry")
	proto.RegisterMapType((map[string]int64)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.StringSfixed64MapEntry")
	proto.RegisterMapType((map[string]int32)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.StringSint32MapEntry")
	proto.RegisterMapType((map[string]int64)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.StringSint64MapEntry")
	proto.RegisterMapType((map[string]string)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.StringStringMapEntry")
	proto.RegisterMapType((map[string]uint32)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.StringUint32MapEntry")
	proto.RegisterMapType((map[string]uint64)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.StringUint64MapEntry")
	proto.RegisterMapType((map[uint32]string)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.Uint32StringMapEntry")
	proto.RegisterMapType((map[uint64]string)(nil), "thethings.fieldsetters.test.MessageWithScalarMaps.Uint64StringMapEntry")
}

func init() { proto.RegisterFile("scalars.proto", fileDescriptor_5d1bcd1a4bdfc194) }

var fileDescriptor_5d1bcd1a4bdfc194 = []byte{
	// 1425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x59, 0x5d, 0x4f, 0xe3, 0x46,
	0x17, 0xc6, 0x99, 0x7c, 0x8e, 0xed, 0x7c, 0x18, 0x58, 0x0c, 0xbc, 0xbc, 0x0c, 0xa0, 0x55, 0xe7,
	0x86, 0x20, 0xed, 0x46, 0x51, 0xd5, 0x9b, 0xb6, 0x74, 0x3f, 0xc2, 0x05, 0xaa, 0x34, 0xd9, 0x6d,
	0xa5, 0xde, 0xac, 0x12, 0x70, 0x42, 0xd4, 0x10, 0x23, 0xc6, 0x5e, 0x95, 0xbf, 0xd4, 0xdf, 0xd2,
	0xfe, 0x90, 0xfe, 0x85, 0x5e, 0x55, 0x33, 0x1e, 0xdb, 0x33, 0x63, 0x83, 0x43, 0xc2, 0xdd, 0xee,
	0xc9, 0xd1, 0xf3, 0x3c, 0x67, 0x9e, 0x73, 0xce, 0x8c, 0x05, 0xb4, 0xe9, 0xd5, 0x68, 0x3e, 0xba,
	0xa7, 0xdd, 0xbb, 0x7b, 0x3f, 0xf0, 0x9d, 0xfd, 0xe0, 0xc6, 0x0b, 0x6e, 0x66, 0x8b, 0x29, 0xed,
	0x4e, 0x66, 0xde, 0xfc, 0x9a, 0x7a, 0x41, 0xe0, 0xdd, 0xd3, 0x6e, 0xe0, 0xd1, 0x60, 0xaf, 0x33,
	0x5a, 0x2c, 0xfc, 0x60, 0x14, 0xcc, 0xfc, 0x85, 0xc8, 0x3f, 0xfe, 0xab, 0x0e, 0x9d, 0x4b, 0x8f,
	0xd2, 0xd1, 0xd4, 0xfb, 0x75, 0x16, 0xdc, 0x0c, 0x23, 0x30, 0xe7, 0x08, 0x5a, 0xd7, 0x7e, 0x38,
	0x9e, 0x7b, 0x5f, 0xbe, 0x8e, 0xe6, 0xa1, 0xe7, 0x1a, 0xc8, 0xc0, 0x06, 0x31, 0xa3, 0xd8, 0x2f,
	0x2c, 0xe4, 0x9c, 0x40, 0x5b, 0x4e, 0xa1, 0x6e, 0x09, 0x01, 0x6c, 0x10, 0x4b, 0xca, 0xa1, 0xce,
	0x21, 0x34, 0x27, 0x73, 0x7f, 0x14, 0x08, 0x18, 0x80, 0x0c, 0x5c, 0x22, 0x90, 0x87, 0x22, 0x94,
	0x23, 0x68, 0x49, 0x09, 0xd4, 0x2d, 0x23, 0x80, 0x4b, 0xc4, 0x4c, 0x33, 0x38, 0xc6, 0x6c, 0x11,
	0xbc, 0x7d, 0x23, 0x30, 0x2a, 0xc8, 0xc0, 0x15, 0x02, 0x79, 0x28, 0xc1, 0x90, 0x12, 0xa8, 0x5b,
	0x45, 0x00, 0x57, 0x88, 0x99, 0x66, 0xc4, 0x18, 0xfd, 0x9e, 0xc0, 0xa8, 0x21, 0x03, 0x03, 0x8e,
	0xd1, 0xef, 0xc9, 0x18, 0x71, 0x02, 0x75, 0xeb, 0x08, 0x60, 0x40, 0xcc, 0x34, 0x83, 0x9f, 0x49,
	0x28, 0x0b, 0x69, 0x20, 0x03, 0xdb, 0xc4, 0x0c, 0x25, 0x25, 0x27, 0xd0, 0x0e, 0x15, 0x29, 0x10,
	0x01, 0x6c, 0x13, 0x2b, 0x94, 0xb5, 0x08, 0x9c, 0x44, 0x8c, 0x89, 0x0c, 0x5c, 0x8e, 0x70, 0x62,
	0x35, 0x02, 0x27, 0x95, 0x63, 0x21, 0x80, 0xcb, 0xc4, 0x0a, 0x35, 0x3d, 0x54, 0xd6, 0x63, 0x23,
	0x03, 0x77, 0x88, 0x49, 0x55, 0x3d, 0x54, 0xd1, 0xd3, 0x44, 0x00, 0x77, 0x88, 0x45, 0x35, 0x3d,
	0x54, 0xd6, 0xd3, 0x42, 0x06, 0x76, 0x22, 0x1c, 0x49, 0x0f, 0x55, 0xf4, 0xb4, 0x11, 0xc0, 0x0e,
	0xb1, 0xa8, 0xac, 0xe7, 0x04, 0xda, 0x93, 0xd9, 0x1f, 0xde, 0x75, 0x22, 0xa8, 0x83, 0x0c, 0x5c,
	0x23, 0x96, 0x08, 0x46, 0x48, 0xaf, 0x61, 0x53, 0x49, 0xa2, 0xae, 0x83, 0x00, 0xae, 0x11, 0x5b,
	0xce, 0x4a, 0xb1, 0x12, 0x51, 0x9b, 0xc8, 0xc0, 0x55, 0x81, 0x15, 0xab, 0x8a, 0xb1, 0x52, 0x59,
	0x5b, 0x08, 0xe0, 0x2a, 0xb1, 0xe5, 0x2c, 0xca, 0xd2, 0xa8, 0x2a, 0x6c, 0x1b, 0x19, 0xb8, 0x45,
	0x6c, 0xaa, 0x28, 0xfb, 0x06, 0xb6, 0xa8, 0x26, 0xed, 0x15, 0x02, 0xb8, 0x45, 0x9a, 0x54, 0xd5,
	0x96, 0xe0, 0x25, 0xe2, 0x76, 0x90, 0x81, 0xdb, 0x31, 0x5e, 0xac, 0x2e, 0xc1, 0x4b, 0xe5, 0xb9,
	0x08, 0xe0, 0x36, 0x69, 0x52, 0x55, 0xdf, 0x01, 0x84, 0x63, 0xdf, 0x9f, 0x0b, 0xac, 0x5d, 0x64,
	0xe0, 0x3a, 0x69, 0xb0, 0x48, 0x84, 0x73, 0x08, 0xcd, 0xf4, 0x67, 0xea, 0xee, 0x21, 0x80, 0xeb,
	0x04, 0x26, 0xbf, 0x47, 0xfe, 0x05, 0xf7, 0xb3, 0xc5, 0x54, 0x20, 0xec, 0x23, 0x03, 0x37, 0x88,
	0x19, 0xc5, 0x52, 0xff, 0xa4, 0x14, 0xea, 0xfe, 0x0f, 0x01, 0xdc, 0x20, 0x96, 0x94, 0xc3, 0x67,
	0x64, 0xfc, 0x10, 0x78, 0x54, 0xc0, 0x1c, 0x20, 0x03, 0x5b, 0x04, 0xf2, 0x50, 0x32, 0x23, 0x52,
	0x02, 0x75, 0xff, 0x8f, 0x00, 0xb6, 0x88, 0x99, 0x66, 0xd0, 0xe3, 0xbf, 0xcb, 0x70, 0x47, 0x5a,
	0x27, 0x3f, 0x2f, 0x3c, 0x7f, 0x12, 0xef, 0x94, 0x93, 0xbc, 0x9d, 0x32, 0xd8, 0x50, 0xb7, 0xca,
	0x91, 0xba, 0x30, 0x4a, 0x6c, 0x61, 0x0c, 0x36, 0xb4, 0x95, 0xa1, 0xec, 0x03, 0xb6, 0x53, 0x2a,
	0x2c, 0x45, 0xd9, 0x08, 0xca, 0xb8, 0x97, 0xd9, 0xb8, 0x8b, 0x94, 0xb4, 0xa5, 0xd5, 0x69, 0x66,
	0x6b, 0xc5, 0x66, 0x6a, 0xd4, 0x79, 0x56, 0x47, 0xb5, 0xca, 0x46, 0x35, 0x4e, 0x92, 0x90, 0x94,
	0x39, 0x64, 0xcb, 0xa5, 0xc3, 0x92, 0xd4, 0x49, 0x54, 0x87, 0xac, 0xce, 0x86, 0x2c, 0x4e, 0x4a,
	0x1b, 0x5a, 0x9b, 0x20, 0xb6, 0x62, 0x6a, 0x83, 0x8d, 0xcc, 0x0c, 0x69, 0xc3, 0x01, 0xd9, 0x70,
	0x24, 0x69, 0x69, 0x03, 0xea, 0x7d, 0xcf, 0x36, 0x4d, 0x6b, 0xb0, 0x91, 0xed, 0x7c, 0xbd, 0xa1,
	0x2d, 0xd6, 0xd0, 0x69, 0x62, 0x8c, 0x78, 0xa8, 0x74, 0x2a, 0xdb, 0x37, 0xf5, 0xc1, 0x86, 0xdc,
	0xab, 0x27, 0x5a, 0x2b, 0x36, 0x59, 0x2b, 0xf2, 0x2a, 0xa5, 0x66, 0x3c, 0x52, 0xfb, 0x8c, 0xad,
	0x1b, 0x8b, 0x99, 0x93, 0xf6, 0xd1, 0x79, 0x0d, 0x56, 0xf8, 0x8f, 0xc7, 0xff, 0xbc, 0x86, 0xdb,
	0x99, 0xeb, 0xe9, 0x72, 0x74, 0x47, 0x1d, 0x0a, 0x3b, 0x82, 0x4a, 0x34, 0xd5, 0xed, 0xe8, 0xce,
	0x35, 0x10, 0xc0, 0xe6, 0x9b, 0x8f, 0xdd, 0x27, 0x2e, 0xc1, 0x6e, 0x2e, 0x5c, 0x77, 0xc8, 0xb1,
	0xde, 0x71, 0xa8, 0xcb, 0xd1, 0xdd, 0xfb, 0x45, 0x70, 0xff, 0x40, 0x5a, 0x54, 0x8d, 0x3a, 0x77,
	0xb0, 0x2d, 0x48, 0xa3, 0x26, 0x65, 0x9c, 0x80, 0x73, 0x7e, 0x58, 0x99, 0xf3, 0x03, 0x43, 0x4a,
	0x28, 0x9b, 0x54, 0x09, 0x4a, 0x8c, 0x51, 0x8b, 0x31, 0xc6, 0xca, 0x9a, 0x8c, 0x17, 0x0c, 0x49,
	0x67, 0x8c, 0x83, 0x8c, 0x31, 0xa2, 0x12, 0xbc, 0x8c, 0xb1, 0xba, 0x32, 0x23, 0x87, 0x8d, 0x68,
	0x53, 0xc6, 0x99, 0x12, 0x54, 0x6b, 0xec, 0xf7, 0x38, 0x63, 0x6d, 0xfd, 0x1a, 0xfb, 0xbd, 0x9c,
	0x1a, 0x79, 0x50, 0xd4, 0xd8, 0xef, 0xc9, 0x35, 0xd6, 0xd7, 0xa9, 0xb1, 0xdf, 0xcb, 0xa9, 0x51,
	0x0a, 0x4a, 0xed, 0x1a, 0xa6, 0x46, 0x36, 0xd6, 0x6c, 0xd7, 0xcf, 0x33, 0xc5, 0x49, 0xd1, 0xae,
	0x49, 0x94, 0x91, 0x86, 0x19, 0x2f, 0xe1, 0xca, 0xa4, 0x9f, 0x67, 0x39, 0x66, 0xb6, 0x42, 0xcd,
	0x4d, 0xb5, 0x52, 0x61, 0xa7, 0xf9, 0x02, 0x95, 0x4a, 0x7e, 0x4a, 0x95, 0x46, 0x86, 0x8a, 0x4a,
	0x55, 0x47, 0xad, 0xb5, 0x2a, 0xcd, 0x58, 0xda, 0x0a, 0x1f, 0xf5, 0x94, 0xa6, 0x9e, 0xda, 0x6b,
	0x56, 0x3a, 0xcc, 0xf5, 0x74, 0x28, 0x7b, 0x4a, 0x33, 0x9e, 0x36, 0x57, 0x27, 0xcd, 0xf5, 0x94,
	0x3e, 0xea, 0x29, 0x4d, 0x3d, 0x6d, 0xbd, 0x40, 0xa5, 0x59, 0x4f, 0x87, 0xb2, 0xa7, 0x34, 0xe3,
	0x69, 0x7b, 0xad, 0x4a, 0xb3, 0x9e, 0x52, 0xcd, 0xd3, 0xaf, 0xd0, 0x89, 0x37, 0xbc, 0xb8, 0x3a,
	0x19, 0x6b, 0x87, 0xb3, 0x0e, 0x56, 0xdf, 0xf1, 0x11, 0x56, 0x42, 0x2b, 0xf6, 0x5d, 0x1a, 0x66,
	0xbc, 0x31, 0xa1, 0x54, 0xad, 0xb3, 0x32, 0xaf, 0x80, 0xd6, 0xca, 0x6d, 0x4f, 0xb4, 0xb0, 0x5e,
	0xaf, 0xb0, 0x76, 0xf3, 0x25, 0xea, 0x95, 0xbc, 0x95, 0xeb, 0x8d, 0xcc, 0x8d, 0xeb, 0x55, 0xdd,
	0xdd, 0x5a, 0xaf, 0xde, 0x8c, 0xbd, 0xed, 0x89, 0x16, 0x76, 0x1e, 0xe0, 0x66, 0xdc, 0xc9, 0xb2,
	0xc1, 0xdb, 0x9c, 0xf8, 0x62, 0xf5, 0x5e, 0x9e, 0x68, 0x0e, 0x8b, 0x79, 0x91, 0xe2, 0x9c, 0x3a,
	0xc7, 0xe3, 0x57, 0xab, 0x53, 0x4f, 0x72, 0x4d, 0xee, 0xd0, 0x8c, 0xcb, 0x7a, 0xd5, 0xc2, 0xe6,
	0x9d, 0x17, 0xa9, 0x5a, 0xf2, 0x59, 0xa9, 0x3a, 0x32, 0x3a, 0xa9, 0x5a, 0x75, 0xda, 0x5d, 0xb3,
	0xea, 0x8c, 0xd5, 0x1d, 0x9a, 0xf1, 0xfa, 0x16, 0x8a, 0x9d, 0xf2, 0x85, 0xbf, 0x5a, 0x19, 0xed,
	0x2e, 0xa7, 0x7d, 0xbf, 0x72, 0xc5, 0xe7, 0xbe, 0x3f, 0x4f, 0x28, 0xc5, 0x37, 0x95, 0x88, 0x31,
	0x3a, 0xce, 0x23, 0x55, 0xb9, 0xb7, 0x32, 0x1d, 0x03, 0xd5, 0x2a, 0xb4, 0xc7, 0x72, 0x4c, 0xde,
	0xc9, 0x29, 0xe1, 0xfe, 0xba, 0x3b, 0x59, 0x5f, 0x8f, 0x6a, 0x54, 0x7a, 0xaa, 0x45, 0x4f, 0x78,
	0xc6, 0x79, 0xb0, 0xe6, 0x53, 0xed, 0x9c, 0x21, 0xe9, 0x4f, 0xb5, 0x38, 0xb8, 0x77, 0x0e, 0xb7,
	0xf2, 0xde, 0xe6, 0x4e, 0x1b, 0x82, 0xdf, 0xbd, 0x07, 0xfe, 0x11, 0xd9, 0x20, 0xec, 0x9f, 0xce,
	0x96, 0xf8, 0x68, 0xe0, 0x1f, 0x8d, 0x06, 0x89, 0xfe, 0xf3, 0x5d, 0xe9, 0x5b, 0x63, 0xef, 0x47,
	0xb8, 0x99, 0xf3, 0xd6, 0x2e, 0x82, 0x28, 0xe5, 0x42, 0x28, 0x8f, 0xe7, 0x22, 0x88, 0x8a, 0x06,
	0x91, 0xf3, 0x1a, 0x96, 0x21, 0x2a, 0x39, 0x10, 0x8d, 0xc7, 0x54, 0xa4, 0x63, 0x57, 0xa4, 0x02,
	0x64, 0x55, 0xe8, 0xe3, 0x23, 0x43, 0x80, 0x22, 0x15, 0x89, 0x25, 0xea, 0xfb, 0xb3, 0x48, 0x86,
	0xad, 0x61, 0xe4, 0x3d, 0x27, 0x65, 0x0c, 0xfb, 0x59, 0x3a, 0x96, 0x3f, 0x8e, 0x72, 0x8e, 0x8e,
	0xa7, 0xce, 0xa3, 0xbc, 0xb4, 0x8e, 0xe1, 0xb3, 0xce, 0xa3, 0xa3, 0x63, 0x14, 0x9c, 0x47, 0xe7,
	0x59, 0x3a, 0x96, 0x3f, 0x0f, 0x27, 0x47, 0xc7, 0x53, 0xe7, 0xe1, 0x14, 0xe9, 0xf8, 0x09, 0x6e,
	0xe7, 0x3e, 0x7b, 0x8a, 0x84, 0xd4, 0x34, 0x90, 0xdc, 0x37, 0x8c, 0x0c, 0x52, 0x7b, 0x9e, 0x92,
	0xe5, 0x8f, 0xa4, 0x9a, 0xa7, 0xe4, 0xa9, 0x33, 0xa9, 0x16, 0x29, 0x79, 0x07, 0x5f, 0xe5, 0xbf,
	0x14, 0x8a, 0xa4, 0xb4, 0x74, 0x94, 0x49, 0xd1, 0xa9, 0xb4, 0x9e, 0xa9, 0x65, 0xf9, 0x63, 0x69,
	0xe7, 0x6a, 0x79, 0xea, 0x5c, 0xda, 0x45, 0x5a, 0x7e, 0x80, 0x4e, 0xf6, 0x66, 0x2d, 0xd2, 0x51,
	0xd7, 0x10, 0xb2, 0x97, 0xa5, 0x8c, 0x50, 0x5f, 0x7e, 0x6e, 0x1e, 0xc5, 0x68, 0x2c, 0xbd, 0x99,
	0x95, 0xdb, 0xac, 0x08, 0xc2, 0x92, 0x20, 0xce, 0x3f, 0xfe, 0xfb, 0xe7, 0x6e, 0xa9, 0x6e, 0xfc,
	0xf6, 0xfd, 0x74, 0x16, 0xdc, 0x84, 0xe3, 0xee, 0x95, 0x7f, 0x7b, 0xf6, 0xe9, 0xc6, 0xfb, 0xc4,
	0xef, 0xd4, 0x8b, 0xc5, 0x75, 0xc8, 0x6e, 0x46, 0x8f, 0x9e, 0xf1, 0x3f, 0xdc, 0x5c, 0x9d, 0x4e,
	0xbd, 0xc5, 0xe9, 0xd4, 0x3f, 0xe5, 0x77, 0xed, 0xa9, 0xb8, 0x6c, 0xcf, 0xd8, 0x65, 0x3b, 0xae,
	0xf2, 0x8c, 0xb7, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x20, 0x96, 0x8c, 0x1b, 0x1a, 0x00,
	0x00,
}
