// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: wkts.proto

package test

import (
	fmt "fmt"
	_ "github.com/TheThingsIndustries/protoc-gen-go-fieldmask/annotations"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MessageWithWKTs struct {
	DoubleValue          *types.DoubleValue   `protobuf:"bytes,1,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	DoubleValues         []*types.DoubleValue `protobuf:"bytes,2,rep,name=double_values,json=doubleValues,proto3" json:"double_values,omitempty"`
	FloatValue           *types.FloatValue    `protobuf:"bytes,3,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	FloatValues          []*types.FloatValue  `protobuf:"bytes,4,rep,name=float_values,json=floatValues,proto3" json:"float_values,omitempty"`
	Int32Value           *types.Int32Value    `protobuf:"bytes,5,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Int32Values          []*types.Int32Value  `protobuf:"bytes,6,rep,name=int32_values,json=int32Values,proto3" json:"int32_values,omitempty"`
	Int64Value           *types.Int64Value    `protobuf:"bytes,7,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Int64Values          []*types.Int64Value  `protobuf:"bytes,8,rep,name=int64_values,json=int64Values,proto3" json:"int64_values,omitempty"`
	Uint32Value          *types.UInt32Value   `protobuf:"bytes,9,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	Uint32Values         []*types.UInt32Value `protobuf:"bytes,10,rep,name=uint32_values,json=uint32Values,proto3" json:"uint32_values,omitempty"`
	Uint64Value          *types.UInt64Value   `protobuf:"bytes,11,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	Uint64Values         []*types.UInt64Value `protobuf:"bytes,12,rep,name=uint64_values,json=uint64Values,proto3" json:"uint64_values,omitempty"`
	BoolValue            *types.BoolValue     `protobuf:"bytes,13,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	BoolValues           []*types.BoolValue   `protobuf:"bytes,14,rep,name=bool_values,json=boolValues,proto3" json:"bool_values,omitempty"`
	StringValue          *types.StringValue   `protobuf:"bytes,15,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	StringValues         []*types.StringValue `protobuf:"bytes,16,rep,name=string_values,json=stringValues,proto3" json:"string_values,omitempty"`
	BytesValue           *types.BytesValue    `protobuf:"bytes,17,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	BytesValues          []*types.BytesValue  `protobuf:"bytes,18,rep,name=bytes_values,json=bytesValues,proto3" json:"bytes_values,omitempty"`
	EmptyValue           *types.Empty         `protobuf:"bytes,19,opt,name=empty_value,json=emptyValue,proto3" json:"empty_value,omitempty"`
	EmptyValues          []*types.Empty       `protobuf:"bytes,20,rep,name=empty_values,json=emptyValues,proto3" json:"empty_values,omitempty"`
	TimestampValue       *types.Timestamp     `protobuf:"bytes,21,opt,name=timestamp_value,json=timestampValue,proto3" json:"timestamp_value,omitempty"`
	TimestampValues      []*types.Timestamp   `protobuf:"bytes,22,rep,name=timestamp_values,json=timestampValues,proto3" json:"timestamp_values,omitempty"`
	DurationValue        *types.Duration      `protobuf:"bytes,23,opt,name=duration_value,json=durationValue,proto3" json:"duration_value,omitempty"`
	DurationValues       []*types.Duration    `protobuf:"bytes,24,rep,name=duration_values,json=durationValues,proto3" json:"duration_values,omitempty"`
	FieldMaskValue       *types.FieldMask     `protobuf:"bytes,25,opt,name=field_mask_value,json=fieldMaskValue,proto3" json:"field_mask_value,omitempty"`
	FieldMaskValues      []*types.FieldMask   `protobuf:"bytes,26,rep,name=field_mask_values,json=fieldMaskValues,proto3" json:"field_mask_values,omitempty"`
	ValueValue           *types.Value         `protobuf:"bytes,27,opt,name=value_value,json=valueValue,proto3" json:"value_value,omitempty"`
	ValueValues          []*types.Value       `protobuf:"bytes,28,rep,name=value_values,json=valueValues,proto3" json:"value_values,omitempty"`
	ListValueValue       *types.ListValue     `protobuf:"bytes,29,opt,name=list_value_value,json=listValueValue,proto3" json:"list_value_value,omitempty"`
	ListValueValues      []*types.ListValue   `protobuf:"bytes,30,rep,name=list_value_values,json=listValueValues,proto3" json:"list_value_values,omitempty"`
	StructValue          *types.Struct        `protobuf:"bytes,31,opt,name=struct_value,json=structValue,proto3" json:"struct_value,omitempty"`
	StructValues         []*types.Struct      `protobuf:"bytes,32,rep,name=struct_values,json=structValues,proto3" json:"struct_values,omitempty"`
	AnyValue             *types.Any           `protobuf:"bytes,33,opt,name=any_value,json=anyValue,proto3" json:"any_value,omitempty"`
	AnyValues            []*types.Any         `protobuf:"bytes,34,rep,name=any_values,json=anyValues,proto3" json:"any_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MessageWithWKTs) Reset()         { *m = MessageWithWKTs{} }
func (m *MessageWithWKTs) String() string { return proto.CompactTextString(m) }
func (*MessageWithWKTs) ProtoMessage()    {}
func (*MessageWithWKTs) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f76f3479ade79d3, []int{0}
}
func (m *MessageWithWKTs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithWKTs.Unmarshal(m, b)
}
func (m *MessageWithWKTs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithWKTs.Marshal(b, m, deterministic)
}
func (m *MessageWithWKTs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithWKTs.Merge(m, src)
}
func (m *MessageWithWKTs) XXX_Size() int {
	return xxx_messageInfo_MessageWithWKTs.Size(m)
}
func (m *MessageWithWKTs) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithWKTs.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithWKTs proto.InternalMessageInfo

func (m *MessageWithWKTs) GetDoubleValue() *types.DoubleValue {
	if m != nil {
		return m.DoubleValue
	}
	return nil
}

func (m *MessageWithWKTs) GetDoubleValues() []*types.DoubleValue {
	if m != nil {
		return m.DoubleValues
	}
	return nil
}

func (m *MessageWithWKTs) GetFloatValue() *types.FloatValue {
	if m != nil {
		return m.FloatValue
	}
	return nil
}

func (m *MessageWithWKTs) GetFloatValues() []*types.FloatValue {
	if m != nil {
		return m.FloatValues
	}
	return nil
}

func (m *MessageWithWKTs) GetInt32Value() *types.Int32Value {
	if m != nil {
		return m.Int32Value
	}
	return nil
}

func (m *MessageWithWKTs) GetInt32Values() []*types.Int32Value {
	if m != nil {
		return m.Int32Values
	}
	return nil
}

func (m *MessageWithWKTs) GetInt64Value() *types.Int64Value {
	if m != nil {
		return m.Int64Value
	}
	return nil
}

func (m *MessageWithWKTs) GetInt64Values() []*types.Int64Value {
	if m != nil {
		return m.Int64Values
	}
	return nil
}

func (m *MessageWithWKTs) GetUint32Value() *types.UInt32Value {
	if m != nil {
		return m.Uint32Value
	}
	return nil
}

func (m *MessageWithWKTs) GetUint32Values() []*types.UInt32Value {
	if m != nil {
		return m.Uint32Values
	}
	return nil
}

func (m *MessageWithWKTs) GetUint64Value() *types.UInt64Value {
	if m != nil {
		return m.Uint64Value
	}
	return nil
}

func (m *MessageWithWKTs) GetUint64Values() []*types.UInt64Value {
	if m != nil {
		return m.Uint64Values
	}
	return nil
}

func (m *MessageWithWKTs) GetBoolValue() *types.BoolValue {
	if m != nil {
		return m.BoolValue
	}
	return nil
}

func (m *MessageWithWKTs) GetBoolValues() []*types.BoolValue {
	if m != nil {
		return m.BoolValues
	}
	return nil
}

func (m *MessageWithWKTs) GetStringValue() *types.StringValue {
	if m != nil {
		return m.StringValue
	}
	return nil
}

func (m *MessageWithWKTs) GetStringValues() []*types.StringValue {
	if m != nil {
		return m.StringValues
	}
	return nil
}

func (m *MessageWithWKTs) GetBytesValue() *types.BytesValue {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

func (m *MessageWithWKTs) GetBytesValues() []*types.BytesValue {
	if m != nil {
		return m.BytesValues
	}
	return nil
}

func (m *MessageWithWKTs) GetEmptyValue() *types.Empty {
	if m != nil {
		return m.EmptyValue
	}
	return nil
}

func (m *MessageWithWKTs) GetEmptyValues() []*types.Empty {
	if m != nil {
		return m.EmptyValues
	}
	return nil
}

func (m *MessageWithWKTs) GetTimestampValue() *types.Timestamp {
	if m != nil {
		return m.TimestampValue
	}
	return nil
}

func (m *MessageWithWKTs) GetTimestampValues() []*types.Timestamp {
	if m != nil {
		return m.TimestampValues
	}
	return nil
}

func (m *MessageWithWKTs) GetDurationValue() *types.Duration {
	if m != nil {
		return m.DurationValue
	}
	return nil
}

func (m *MessageWithWKTs) GetDurationValues() []*types.Duration {
	if m != nil {
		return m.DurationValues
	}
	return nil
}

func (m *MessageWithWKTs) GetFieldMaskValue() *types.FieldMask {
	if m != nil {
		return m.FieldMaskValue
	}
	return nil
}

func (m *MessageWithWKTs) GetFieldMaskValues() []*types.FieldMask {
	if m != nil {
		return m.FieldMaskValues
	}
	return nil
}

func (m *MessageWithWKTs) GetValueValue() *types.Value {
	if m != nil {
		return m.ValueValue
	}
	return nil
}

func (m *MessageWithWKTs) GetValueValues() []*types.Value {
	if m != nil {
		return m.ValueValues
	}
	return nil
}

func (m *MessageWithWKTs) GetListValueValue() *types.ListValue {
	if m != nil {
		return m.ListValueValue
	}
	return nil
}

func (m *MessageWithWKTs) GetListValueValues() []*types.ListValue {
	if m != nil {
		return m.ListValueValues
	}
	return nil
}

func (m *MessageWithWKTs) GetStructValue() *types.Struct {
	if m != nil {
		return m.StructValue
	}
	return nil
}

func (m *MessageWithWKTs) GetStructValues() []*types.Struct {
	if m != nil {
		return m.StructValues
	}
	return nil
}

func (m *MessageWithWKTs) GetAnyValue() *types.Any {
	if m != nil {
		return m.AnyValue
	}
	return nil
}

func (m *MessageWithWKTs) GetAnyValues() []*types.Any {
	if m != nil {
		return m.AnyValues
	}
	return nil
}

type MessageWithOneofWKTs struct {
	// Types that are valid to be assigned to Value:
	//	*MessageWithOneofWKTs_DoubleValue
	//	*MessageWithOneofWKTs_FloatValue
	//	*MessageWithOneofWKTs_Int32Value
	//	*MessageWithOneofWKTs_Int64Value
	//	*MessageWithOneofWKTs_Uint32Value
	//	*MessageWithOneofWKTs_Uint64Value
	//	*MessageWithOneofWKTs_BoolValue
	//	*MessageWithOneofWKTs_StringValue
	//	*MessageWithOneofWKTs_BytesValue
	//	*MessageWithOneofWKTs_EmptyValue
	//	*MessageWithOneofWKTs_TimestampValue
	//	*MessageWithOneofWKTs_DurationValue
	//	*MessageWithOneofWKTs_FieldMaskValue
	//	*MessageWithOneofWKTs_ValueValue
	//	*MessageWithOneofWKTs_ListValueValue
	//	*MessageWithOneofWKTs_StructValue
	//	*MessageWithOneofWKTs_AnyValue
	Value                isMessageWithOneofWKTs_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *MessageWithOneofWKTs) Reset()         { *m = MessageWithOneofWKTs{} }
func (m *MessageWithOneofWKTs) String() string { return proto.CompactTextString(m) }
func (*MessageWithOneofWKTs) ProtoMessage()    {}
func (*MessageWithOneofWKTs) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f76f3479ade79d3, []int{1}
}
func (m *MessageWithOneofWKTs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithOneofWKTs.Unmarshal(m, b)
}
func (m *MessageWithOneofWKTs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithOneofWKTs.Marshal(b, m, deterministic)
}
func (m *MessageWithOneofWKTs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithOneofWKTs.Merge(m, src)
}
func (m *MessageWithOneofWKTs) XXX_Size() int {
	return xxx_messageInfo_MessageWithOneofWKTs.Size(m)
}
func (m *MessageWithOneofWKTs) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithOneofWKTs.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithOneofWKTs proto.InternalMessageInfo

type isMessageWithOneofWKTs_Value interface {
	isMessageWithOneofWKTs_Value()
}

type MessageWithOneofWKTs_DoubleValue struct {
	DoubleValue *types.DoubleValue `protobuf:"bytes,1,opt,name=double_value,json=doubleValue,proto3,oneof" json:"double_value,omitempty"`
}
type MessageWithOneofWKTs_FloatValue struct {
	FloatValue *types.FloatValue `protobuf:"bytes,2,opt,name=float_value,json=floatValue,proto3,oneof" json:"float_value,omitempty"`
}
type MessageWithOneofWKTs_Int32Value struct {
	Int32Value *types.Int32Value `protobuf:"bytes,3,opt,name=int32_value,json=int32Value,proto3,oneof" json:"int32_value,omitempty"`
}
type MessageWithOneofWKTs_Int64Value struct {
	Int64Value *types.Int64Value `protobuf:"bytes,4,opt,name=int64_value,json=int64Value,proto3,oneof" json:"int64_value,omitempty"`
}
type MessageWithOneofWKTs_Uint32Value struct {
	Uint32Value *types.UInt32Value `protobuf:"bytes,5,opt,name=uint32_value,json=uint32Value,proto3,oneof" json:"uint32_value,omitempty"`
}
type MessageWithOneofWKTs_Uint64Value struct {
	Uint64Value *types.UInt64Value `protobuf:"bytes,6,opt,name=uint64_value,json=uint64Value,proto3,oneof" json:"uint64_value,omitempty"`
}
type MessageWithOneofWKTs_BoolValue struct {
	BoolValue *types.BoolValue `protobuf:"bytes,7,opt,name=bool_value,json=boolValue,proto3,oneof" json:"bool_value,omitempty"`
}
type MessageWithOneofWKTs_StringValue struct {
	StringValue *types.StringValue `protobuf:"bytes,8,opt,name=string_value,json=stringValue,proto3,oneof" json:"string_value,omitempty"`
}
type MessageWithOneofWKTs_BytesValue struct {
	BytesValue *types.BytesValue `protobuf:"bytes,9,opt,name=bytes_value,json=bytesValue,proto3,oneof" json:"bytes_value,omitempty"`
}
type MessageWithOneofWKTs_EmptyValue struct {
	EmptyValue *types.Empty `protobuf:"bytes,10,opt,name=empty_value,json=emptyValue,proto3,oneof" json:"empty_value,omitempty"`
}
type MessageWithOneofWKTs_TimestampValue struct {
	TimestampValue *types.Timestamp `protobuf:"bytes,11,opt,name=timestamp_value,json=timestampValue,proto3,oneof" json:"timestamp_value,omitempty"`
}
type MessageWithOneofWKTs_DurationValue struct {
	DurationValue *types.Duration `protobuf:"bytes,12,opt,name=duration_value,json=durationValue,proto3,oneof" json:"duration_value,omitempty"`
}
type MessageWithOneofWKTs_FieldMaskValue struct {
	FieldMaskValue *types.FieldMask `protobuf:"bytes,13,opt,name=field_mask_value,json=fieldMaskValue,proto3,oneof" json:"field_mask_value,omitempty"`
}
type MessageWithOneofWKTs_ValueValue struct {
	ValueValue *types.Value `protobuf:"bytes,14,opt,name=value_value,json=valueValue,proto3,oneof" json:"value_value,omitempty"`
}
type MessageWithOneofWKTs_ListValueValue struct {
	ListValueValue *types.ListValue `protobuf:"bytes,15,opt,name=list_value_value,json=listValueValue,proto3,oneof" json:"list_value_value,omitempty"`
}
type MessageWithOneofWKTs_StructValue struct {
	StructValue *types.Struct `protobuf:"bytes,16,opt,name=struct_value,json=structValue,proto3,oneof" json:"struct_value,omitempty"`
}
type MessageWithOneofWKTs_AnyValue struct {
	AnyValue *types.Any `protobuf:"bytes,17,opt,name=any_value,json=anyValue,proto3,oneof" json:"any_value,omitempty"`
}

func (*MessageWithOneofWKTs_DoubleValue) isMessageWithOneofWKTs_Value()    {}
func (*MessageWithOneofWKTs_FloatValue) isMessageWithOneofWKTs_Value()     {}
func (*MessageWithOneofWKTs_Int32Value) isMessageWithOneofWKTs_Value()     {}
func (*MessageWithOneofWKTs_Int64Value) isMessageWithOneofWKTs_Value()     {}
func (*MessageWithOneofWKTs_Uint32Value) isMessageWithOneofWKTs_Value()    {}
func (*MessageWithOneofWKTs_Uint64Value) isMessageWithOneofWKTs_Value()    {}
func (*MessageWithOneofWKTs_BoolValue) isMessageWithOneofWKTs_Value()      {}
func (*MessageWithOneofWKTs_StringValue) isMessageWithOneofWKTs_Value()    {}
func (*MessageWithOneofWKTs_BytesValue) isMessageWithOneofWKTs_Value()     {}
func (*MessageWithOneofWKTs_EmptyValue) isMessageWithOneofWKTs_Value()     {}
func (*MessageWithOneofWKTs_TimestampValue) isMessageWithOneofWKTs_Value() {}
func (*MessageWithOneofWKTs_DurationValue) isMessageWithOneofWKTs_Value()  {}
func (*MessageWithOneofWKTs_FieldMaskValue) isMessageWithOneofWKTs_Value() {}
func (*MessageWithOneofWKTs_ValueValue) isMessageWithOneofWKTs_Value()     {}
func (*MessageWithOneofWKTs_ListValueValue) isMessageWithOneofWKTs_Value() {}
func (*MessageWithOneofWKTs_StructValue) isMessageWithOneofWKTs_Value()    {}
func (*MessageWithOneofWKTs_AnyValue) isMessageWithOneofWKTs_Value()       {}

func (m *MessageWithOneofWKTs) GetValue() isMessageWithOneofWKTs_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetDoubleValue() *types.DoubleValue {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_DoubleValue); ok {
		return x.DoubleValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetFloatValue() *types.FloatValue {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_FloatValue); ok {
		return x.FloatValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetInt32Value() *types.Int32Value {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_Int32Value); ok {
		return x.Int32Value
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetInt64Value() *types.Int64Value {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_Int64Value); ok {
		return x.Int64Value
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetUint32Value() *types.UInt32Value {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_Uint32Value); ok {
		return x.Uint32Value
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetUint64Value() *types.UInt64Value {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_Uint64Value); ok {
		return x.Uint64Value
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetBoolValue() *types.BoolValue {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_BoolValue); ok {
		return x.BoolValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetStringValue() *types.StringValue {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_StringValue); ok {
		return x.StringValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetBytesValue() *types.BytesValue {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetEmptyValue() *types.Empty {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_EmptyValue); ok {
		return x.EmptyValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetTimestampValue() *types.Timestamp {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_TimestampValue); ok {
		return x.TimestampValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetDurationValue() *types.Duration {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_DurationValue); ok {
		return x.DurationValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetFieldMaskValue() *types.FieldMask {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_FieldMaskValue); ok {
		return x.FieldMaskValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetValueValue() *types.Value {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_ValueValue); ok {
		return x.ValueValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetListValueValue() *types.ListValue {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_ListValueValue); ok {
		return x.ListValueValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetStructValue() *types.Struct {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_StructValue); ok {
		return x.StructValue
	}
	return nil
}

func (m *MessageWithOneofWKTs) GetAnyValue() *types.Any {
	if x, ok := m.GetValue().(*MessageWithOneofWKTs_AnyValue); ok {
		return x.AnyValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MessageWithOneofWKTs) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MessageWithOneofWKTs_DoubleValue)(nil),
		(*MessageWithOneofWKTs_FloatValue)(nil),
		(*MessageWithOneofWKTs_Int32Value)(nil),
		(*MessageWithOneofWKTs_Int64Value)(nil),
		(*MessageWithOneofWKTs_Uint32Value)(nil),
		(*MessageWithOneofWKTs_Uint64Value)(nil),
		(*MessageWithOneofWKTs_BoolValue)(nil),
		(*MessageWithOneofWKTs_StringValue)(nil),
		(*MessageWithOneofWKTs_BytesValue)(nil),
		(*MessageWithOneofWKTs_EmptyValue)(nil),
		(*MessageWithOneofWKTs_TimestampValue)(nil),
		(*MessageWithOneofWKTs_DurationValue)(nil),
		(*MessageWithOneofWKTs_FieldMaskValue)(nil),
		(*MessageWithOneofWKTs_ValueValue)(nil),
		(*MessageWithOneofWKTs_ListValueValue)(nil),
		(*MessageWithOneofWKTs_StructValue)(nil),
		(*MessageWithOneofWKTs_AnyValue)(nil),
	}
}

func init() {
	proto.RegisterType((*MessageWithWKTs)(nil), "thethings.fieldmask.test.MessageWithWKTs")
	proto.RegisterType((*MessageWithOneofWKTs)(nil), "thethings.fieldmask.test.MessageWithOneofWKTs")
}

func init() { proto.RegisterFile("wkts.proto", fileDescriptor_4f76f3479ade79d3) }

var fileDescriptor_4f76f3479ade79d3 = []byte{
	// 1029 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0x76, 0xda, 0xfc, 0xd8, 0x94, 0x6c, 0xc7, 0x5a, 0xd6, 0x32, 0x3f, 0x6b, 0xb3, 0x5c, 0xed,
	0x26, 0x0e, 0xd6, 0x14, 0x1d, 0xb2, 0x04, 0xd9, 0xec, 0x35, 0x81, 0x8b, 0xad, 0x18, 0xe0, 0x65,
	0x2b, 0xb0, 0x9b, 0x42, 0xb6, 0x65, 0x5b, 0x88, 0x2c, 0x19, 0x3e, 0x54, 0x8b, 0x3c, 0xc2, 0x5e,
	0x65, 0xcf, 0xb6, 0x27, 0xd8, 0xd5, 0xc0, 0x23, 0x52, 0x24, 0xa5, 0xd0, 0xc2, 0xee, 0x28, 0xf0,
	0x7c, 0xe7, 0x3b, 0x3c, 0x3a, 0xfa, 0x3e, 0x8a, 0x90, 0xcf, 0xf7, 0x0c, 0xba, 0xcb, 0x55, 0xc2,
	0x12, 0x8f, 0xb2, 0x79, 0xc0, 0xe6, 0x61, 0x3c, 0x83, 0xee, 0x34, 0x0c, 0xa2, 0xc9, 0xc2, 0x87,
	0xfb, 0x2e, 0x0b, 0x80, 0x1d, 0x74, 0xfc, 0x38, 0x4e, 0x98, 0xcf, 0xc2, 0x24, 0x16, 0xc1, 0x07,
	0xfb, 0xb3, 0x24, 0x99, 0x45, 0xc1, 0x19, 0x3e, 0x8d, 0xd2, 0xe9, 0x99, 0x1f, 0x3f, 0x88, 0xad,
	0x17, 0xc5, 0xad, 0x49, 0xba, 0x42, 0xac, 0xd8, 0x3f, 0x2c, 0xee, 0x07, 0x8b, 0x25, 0x93, 0xe0,
	0xe3, 0xe2, 0x26, 0x96, 0xf2, 0x11, 0x6b, 0xc9, 0x22, 0x8e, 0x8a, 0x11, 0xc0, 0x56, 0xe9, 0x98,
	0x89, 0xdd, 0x97, 0xc5, 0x5d, 0x16, 0x2e, 0x02, 0x60, 0xfe, 0x62, 0x69, 0xab, 0xee, 0xf3, 0xca,
	0x5f, 0x2e, 0x83, 0x95, 0x38, 0xd8, 0xc9, 0x5f, 0x1d, 0xd2, 0x7e, 0x1f, 0x00, 0xf8, 0xb3, 0xe0,
	0x43, 0xc8, 0xe6, 0x1f, 0x7e, 0xbe, 0x03, 0xef, 0x07, 0xe2, 0x4e, 0x92, 0x74, 0x14, 0x05, 0x1f,
	0x3f, 0xf9, 0x51, 0x1a, 0xd0, 0x8d, 0xe3, 0x8d, 0x6f, 0x9c, 0x57, 0x47, 0xdd, 0x2c, 0x55, 0x57,
	0xa6, 0xea, 0xbe, 0xc5, 0xa0, 0x3f, 0x78, 0xcc, 0xd0, 0x99, 0xa8, 0x07, 0xaf, 0x47, 0x9a, 0x7a,
	0x02, 0xa0, 0x4f, 0x8e, 0x9f, 0x56, 0x66, 0x70, 0xb5, 0x0c, 0xe0, 0x5d, 0x11, 0x67, 0x1a, 0x25,
	0x3e, 0x13, 0x25, 0x3c, 0xc5, 0x12, 0x0e, 0x4b, 0x09, 0x6e, 0x79, 0x4c, 0x86, 0x27, 0xd3, 0x7c,
	0xed, 0x5d, 0x13, 0x57, 0x43, 0x03, 0xdd, 0x44, 0xfe, 0xb5, 0x70, 0x47, 0xc1, 0x91, 0x3d, 0x8c,
	0xd9, 0xf9, 0x2b, 0xc1, 0xbe, 0x65, 0x61, 0x7f, 0xc7, 0x63, 0x04, 0x7b, 0x98, 0xaf, 0x39, 0xbb,
	0x86, 0x06, 0xba, 0x6d, 0x61, 0xd7, 0xe0, 0x8e, 0x82, 0x4b, 0xf6, 0x37, 0xaf, 0x05, 0xfb, 0x8e,
	0x9d, 0xfd, 0xcd, 0x6b, 0xc5, 0x2e, 0xd6, 0x82, 0x5d, 0xa2, 0x81, 0xd6, 0xed, 0xec, 0x12, 0xee,
	0x28, 0x38, 0xbe, 0xfd, 0x54, 0x3f, 0x7c, 0xc3, 0xf2, 0xf6, 0x7f, 0xd7, 0xcb, 0x4f, 0xb5, 0xe3,
	0xf7, 0x48, 0x33, 0x35, 0xce, 0x4f, 0x2c, 0x6f, 0x5f, 0xcf, 0xe0, 0xa6, 0x7a, 0x07, 0x44, 0x0d,
	0x79, 0x0b, 0x9c, 0x35, 0x35, 0xe4, 0x87, 0x48, 0xb5, 0x26, 0x88, 0x1a, 0x54, 0x17, 0xdc, 0x35,
	0x35, 0xc8, 0x0c, 0x6e, 0xaa, 0xf7, 0xe1, 0x82, 0x90, 0x51, 0x92, 0x44, 0xa2, 0x82, 0x26, 0x56,
	0x70, 0x50, 0xc2, 0xf7, 0x93, 0x24, 0xca, 0xd0, 0x8d, 0x91, 0x5c, 0x7a, 0x97, 0xc4, 0x51, 0x50,
	0xa0, 0x2d, 0xe4, 0x5e, 0x87, 0x25, 0x39, 0x16, 0xcf, 0x0e, 0x6c, 0x15, 0xc6, 0x33, 0xc1, 0xdc,
	0xb6, 0x9c, 0xfd, 0x37, 0x0c, 0x12, 0x67, 0x07, 0xf5, 0xc0, 0xcf, 0xae, 0x27, 0x00, 0xba, 0x6b,
	0x39, 0xbb, 0x9e, 0xc1, 0xd5, 0x32, 0xe0, 0x04, 0x8e, 0x1e, 0x58, 0x00, 0xa2, 0x84, 0x8e, 0x65,
	0x02, 0xfb, 0x3c, 0x46, 0x9e, 0x20, 0x5f, 0xf3, 0x09, 0xd4, 0xd0, 0x40, 0x3d, 0xcb, 0x04, 0x6a,
	0x70, 0x47, 0xc1, 0xc1, 0xfb, 0x8e, 0x38, 0xa8, 0x91, 0x82, 0xfd, 0x0b, 0x64, 0x7f, 0x56, 0x82,
	0xdf, 0xf0, 0x98, 0x21, 0xc1, 0xd0, 0x8c, 0xf8, 0x82, 0xb8, 0x1a, 0x10, 0xe8, 0x1e, 0x12, 0xdb,
	0x90, 0x8e, 0x42, 0x82, 0xf7, 0x13, 0x69, 0xe7, 0xd2, 0x29, 0x78, 0xbf, 0xb4, 0xbc, 0xf2, 0x3b,
	0x19, 0x37, 0x6c, 0xe5, 0x90, 0x8c, 0xff, 0x86, 0xec, 0x16, 0x92, 0x00, 0x7d, 0x66, 0x79, 0xf9,
	0x2a, 0x4b, 0xdb, 0xcc, 0x02, 0xde, 0x8f, 0xa4, 0x25, 0x3d, 0x44, 0x94, 0xf2, 0x1c, 0x4b, 0xd9,
	0x2f, 0xeb, 0xa7, 0x08, 0x1b, 0x36, 0x25, 0x20, 0x2b, 0xa4, 0x4f, 0xda, 0x66, 0x06, 0xa0, 0x14,
	0xeb, 0x58, 0x93, 0xa2, 0x65, 0xa4, 0x00, 0xef, 0x2d, 0xd9, 0x55, 0x66, 0x24, 0xea, 0xd8, 0xb7,
	0xb4, 0xe4, 0x96, 0x07, 0xbe, 0xf7, 0xe1, 0x7e, 0xd8, 0x9a, 0xca, 0x65, 0x56, 0xc9, 0x2d, 0xe9,
	0x14, 0xb3, 0x00, 0x3d, 0xb0, 0xf4, 0x44, 0xa5, 0x69, 0x9b, 0x69, 0x70, 0x26, 0x10, 0x2c, 0x0a,
	0x39, 0xb4, 0xcc, 0x84, 0x18, 0x46, 0x0c, 0xca, 0x67, 0x42, 0x03, 0x02, 0x3d, 0xb2, 0xcc, 0x84,
	0x98, 0x43, 0x85, 0xc4, 0x0e, 0x44, 0x21, 0x08, 0x13, 0x11, 0xc4, 0x5f, 0x59, 0x3a, 0xf0, 0x4b,
	0x08, 0xc2, 0x48, 0x5a, 0x91, 0x5c, 0xe6, 0x1d, 0x28, 0x66, 0x01, 0xfa, 0xc2, 0xd2, 0x01, 0x95,
	0xa6, 0x6d, 0xa6, 0x01, 0xef, 0x7b, 0xd4, 0x85, 0x74, 0x2c, 0x2d, 0xf1, 0x25, 0x56, 0xf2, 0xfc,
	0xb1, 0xaf, 0x3a, 0x1d, 0x33, 0x94, 0x84, 0x74, 0x2c, 0xfc, 0xf0, 0x0a, 0x25, 0x21, 0xc7, 0x02,
	0x3d, 0x46, 0x7e, 0x2b, 0xd8, 0xd5, 0xc0, 0xe0, 0x7d, 0x4b, 0x1a, 0x7e, 0x2c, 0xbf, 0xc6, 0xaf,
	0x91, 0x76, 0xaf, 0x84, 0xec, 0xc5, 0x0f, 0xc3, 0xba, 0x1f, 0x8b, 0x2f, 0xf1, 0x9c, 0x90, 0x1c,
	0x02, 0xf4, 0x04, 0xd9, 0x1e, 0xc7, 0x34, 0x24, 0x06, 0x4e, 0xfe, 0xa9, 0x93, 0x3d, 0xed, 0x2e,
	0xf2, 0x6b, 0x1c, 0x24, 0x53, 0xbc, 0x90, 0xf4, 0xfe, 0xff, 0x85, 0x64, 0x50, 0x33, 0xaf, 0x24,
	0xd7, 0xe6, 0x7d, 0xe2, 0x49, 0xe5, 0x7d, 0x62, 0x50, 0x2b, 0xdc, 0x28, 0x8c, 0x1b, 0xc1, 0xd3,
	0xca, 0x1b, 0x01, 0xc7, 0x1b, 0x77, 0x02, 0xc3, 0xd3, 0x37, 0x2b, 0x3d, 0x5d, 0xe0, 0x95, 0xa1,
	0x99, 0xae, 0xbc, 0x55, 0xed, 0xca, 0xbc, 0x05, 0xa6, 0x2f, 0x9b, 0xa6, 0xba, 0x5d, 0x6d, 0xaa,
	0x32, 0x85, 0xac, 0xe2, 0xd2, 0xf0, 0xc4, 0x9d, 0x2a, 0x4f, 0x1c, 0xd4, 0x74, 0x57, 0xec, 0x15,
	0x8c, 0xad, 0x5e, 0x6d, 0x6c, 0x9c, 0x5f, 0xb7, 0xb6, 0x6b, 0xd3, 0x97, 0x1a, 0x95, 0xbe, 0xc4,
	0xbb, 0xa8, 0x39, 0xd3, 0x85, 0xe9, 0x2c, 0x64, 0x9d, 0xb3, 0x70, 0xa8, 0xe6, 0x2d, 0x37, 0x65,
	0x83, 0x70, 0xaa, 0x0c, 0x62, 0x50, 0x2b, 0x59, 0x44, 0xbf, 0xa4, 0xed, 0x6e, 0x85, 0xb6, 0x0f,
	0x6a, 0x45, 0x75, 0xbf, 0x7d, 0x44, 0x99, 0x9b, 0x55, 0xca, 0xcc, 0x6b, 0x29, 0x68, 0xf3, 0x85,
	0xa9, 0xa9, 0xad, 0x75, 0x9a, 0xca, 0xbb, 0xf1, 0x49, 0x17, 0xb5, 0xb2, 0x34, 0xb6, 0xab, 0xa4,
	0x91, 0x97, 0x50, 0x10, 0xc7, 0xab, 0x82, 0xa8, 0xed, 0xae, 0x15, 0x35, 0x31, 0x0e, 0xb9, 0xac,
	0x9d, 0xeb, 0xc2, 0xd4, 0xb1, 0x0b, 0xd3, 0xa0, 0xa6, 0xa4, 0xa9, 0xbf, 0x43, 0xb6, 0x10, 0xd0,
	0xbf, 0xf9, 0xf7, 0xef, 0xfd, 0xcd, 0xfa, 0x06, 0xdd, 0xf8, 0xf3, 0x72, 0x16, 0xb2, 0x79, 0x3a,
	0xea, 0x8e, 0x93, 0xc5, 0xd9, 0xdd, 0x3c, 0xb8, 0xc3, 0xbf, 0xc2, 0x77, 0xf1, 0x24, 0xe5, 0xb3,
	0x17, 0x40, 0xf6, 0xf3, 0x34, 0x3e, 0x9d, 0x05, 0xf1, 0xe9, 0x2c, 0x39, 0xcd, 0xff, 0x16, 0xcf,
	0xf8, 0xdf, 0xe2, 0x68, 0x1b, 0x77, 0xcf, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x67, 0x24, 0x6c,
	0x5a, 0x5c, 0x0e, 0x00, 0x00,
}
