name: Go Code

on:
  - push
  - pull_request

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.24"
      - name: Clean Build
        run: make clean build
      - name: Go Test
        run: make test
